### ISSUE TITLE
Can colourisation be disabled?

### ISSUE THREAD

**Issue by kseistrup** [kuroko-lang/kuroko#21]
In short: can the REPL colourisation ‘theme’ be disabled or changed?

While I like pretty colours, a lot of the text in the kuroko REPL is black on black — even when compiled with `KRK_DISABLE_RLINE=1` or invoked as `kuroko -r` — and thus illegible:

```text
$ kuroko -r
Kuroko 1.1.2 (Nov 14 2021 at 12:59:00) with GCC 11.1.0
Type `help` for guidance, `paste()` to toggle automatic indentation, `license` for copyright information.
>>> help

>>> 2

>>> dir('')


>>>
```

In order to see the output I have to paste it into an editor, which is counter-productive.

**Comment by klange** [comment]
Can you try building the latest master rather than 1.1.2? The problem is likely that your terminal does not interpret bold text as bright, which should be resolved by [https://github.com/kuroko-lang/kuroko/commit/fba00902d45bdb3df4b67f8cd31dcc3113afe026](this commit).

**Comment by kseistrup** [comment]
Thanks, building from the latest master solved my problem.
