### ISSUE TITLE
Compile to native code?

### ISSUE THREAD

**Issue by Justaus3r** [kuroko-lang/kuroko#25]
I appologize if this is a dumb question and i don't suppose it is in your agenda for kuroko's future but  is compiling kuroko to native code on your agenda cuz that will be hella freakin cool.also a seperate question: do you plan on registering kuroko on github linguists as a seperate programming language.usually registering a language requires it to have 200 or so seperate repos written in that language by seperate users.i know it hasn't garner  much attention but just wanted to know  if you had any such plans.

**Comment by klange** [comment]
- Kuroko is intended to be used as an embedded scripting language: it was designed to write extensions and config files for my text editor, and later as a general scripting language for my OS project. With those goals in mind, I built Kuroko to have a small footprint - it requires only a handful of libc functions, has no external dependencies, and can be built for virtually any platform. I consider these to be core aspects of the language.
- Native compilation requires a code gen backend. Some languages go about this by having a "transpiler" that converts source code to another language and then uses that language's compiler to build a binary - this obviously introduces a dependency on another compiler. More mature languages would use a compiler backend like LLVM - which, again, is a large external dependency. The "do it myself" hobbyist approach is to write your own code gen, but that is a dreadfully difficult task, especially if you want any of the performance benefits that are expected from "compiling to native code".
- Kuroko is a dialect of Python, and with that design comes a lot of things that are ill suited to static, native compilation. Most of that isn't so much in the syntax, but in the expectations of the runtime. Building a natively-compiled language with all the same semantics is doable (see Cython, which achieves this by compiling "pure Python" to equivalent C code that uses the CPython APIs to do what the bytecode eval loop would do anyway), but it has limited benefits on its own and it takes a lot of restrictions on the language to see real performance gains.

Would I like to see a Cython equivalent for Kuroko? I think it would be neat. Do I have the time to pursue something like that myself? Not at the moment. And, besides, if and when I do have the opportunity to work on a natively-compiled language, I would make very different design decisions than trying to emulate Python as I have with Kuroko.

**Comment by Justaus3r** [comment]
Ah thanks for letting me know.i know about cython but i thought it used some bulky dlls .there is also another project called nuitka which compiles all python constructs to c and uses libpython.well anyway sorry for the silly question and thanks.
