### ISSUE TITLE
Shouldn't this be `==`?

### ISSUE THREAD

**Issue by TunifyBasic** [kuroko-lang/kuroko#52]
```kuroko
>>> let x = 50
>>> if x = 50:
  >     print("hi")
  >     
hi
>>> if x == 50:
  >     print("hi")
  >     
hi
>>> # witch one should be used?
```

is there any standardone?

**Comment by klange** [comment]
Kuroko has assignment expressions, much like C, but unlike Python which opted to use a different token (`:=`).

The value of an assignment expression is the assigned value, so `(x = 50)` has a value of `50`, and `50` is truthy, so the branch is taken. If you assigned `0` or `False` or `[]` or any other falsey value, the branch would not have been taken.

The possibility of mistakenly assigning where one means to evaluate equality, just by missing an equals sign, is why the Python designers (after some mailinglist debate) opted to require a different token with a colon. This was a relatively recent decision when Kuroko was being designed, and I went a different way.
